sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/twirl/sample.scala.html
これまでは、セリフの色を変更することができなかった。
一般に、発話しているキャラクターによってセリフの色を変更することはよく行われている慣習であるから、zmmでも優先度高く対応させたい。
また、個々のセリフについて毎回設定するのではなく、冒頭のキャラクターコンフィグでデフォルトの色を定めると、特に変更しない限りその色が使われるようになっていてほしい。
- デフォルトコンテキストを導出するさいに、`characterconfig`タグで設定されている`serif-color`をそのキャラクターのセリフのデフォルト色とするようにした
- 個々の`say`要素について、`serif-color`を設定することでコンテキストを導出できるようにした
- コンテキストをもとに、テンプレートがその色を認識して反映させるようにした
- サンプルを更新した
=> セリフの色を変更できるようにしたのだ

sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/twirl/sample.scala.html
キャラクターが喋っているとき、そのキャラクターの立ち絵が表示されるのが普通である。しかしまだ未実装だったので実装する。
- `Context`に`tachieUrl`を導入した。
- キャラクターの標準立ち絵も設定されていて然るべきなので、`characterconfig`で設定できるようにした。
- テンプレートに立ち絵が反映されるようにした。
=> キャラクターの立ち絵を設定できるようにしたのだ

src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala
これまではAVIファイルを挟んでから動画を出力していたが、なぜか画質が荒れるという問題があった。mp4に直接出力するとこのような怪現象が発生しないので、これで行きたい
- 画像結合時に直接mp4をx264コーデックで出力するようにした
=> 画質が荒れる不具合を修正

src/main/scala/com/github/windymelt/zmm/infrastructure/VoiceVox.scala
#6 が壊れていたので直した。
- query parameterのkeyをまちがえていたので直した
- クエリを作るだけで終了して実際は呼び出せていなかったのを直した
=> 辞書登録メカニズムこわれてたので直した

sample.xml, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/twirl/sample.scala.html
セリフの他に解説を表示したいことがほとんどであり、これをなんとかしたい
`motif`属性を設定することにより、簡易的に文字列をそのままテンプレートに出力できるようにした。あくまで簡易なので箇条書きに非対応になっているが今後なんとかしたい。
```xml
<say by="char1" motif="あいさつです">こんにちは〜</say>
=> 簡易的に補足情報の表示ができるようにする

README.md, default.min.css, highlight.min.js, sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/twirl/sample.scala.html
ソースコードを埋め込みたいので埋め込んだ
highlight.jsという便利なやつがある https://highlightjs.org/usage/ のでこれをリポジトリに埋め込んだ。BSD3項ライセンスなのでREADMEにライセンスを追加した。
`content>predef>code`にコードを置けるようにした。コードは`id`属性で識別する必要がある。`lang`属性をサポートしているが、highlight.jsは言語を自動判別するので不要かもしれない。
コードを表示したい箇所では、`code="コードのID"`属性を置くことで表示できる。
また、細微なリファクタリング(長いフィールド名へのエイリアス用意など)を行った。
=> ソースコード埋め込み機能

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/CliOptions.scala, src/main/scala/com/github/windymelt/zmm/Main.scala, src/main/twirl/script.scala.xml
ディレクトリ掘ったりするの面倒だと思うのでそのへんをやってくれるコマンドを作成した。`npm init` とかと同じイメージ。
=> Initコマンドを実装する

sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/twirl/sample.scala.html
`meta`要素の中に`font`タグを配置することで、スライドを通じて利用するフォントを指定できるようにした。
=> セリフのフォントをfontタグで指定できるようにする

sample.xml, src/test/scala/com/github/windymelt/zmm/domain/model/ContextSpec.scala
というか元々そうなっていた。
同一キャラが長回しで喋る長文を毎回`say`タグで書くのが大変だったが、実は`p`タグで区切るだけで良かった。コンテキストは保存される。
=> 空のPタグで発言を分けて書けるようにした

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/CliOptions.scala, src/main/scala/com/github/windymelt/zmm/Main.scala
使ってもらったユーザから問い合わせをもらうことがあるが、バージョン情報などを一手に表示する方法がなかった。動画変換時のロゴにもバージョンは表示されていたが、情報不足な上に使いにくいので単体で`--version`、`-v`を充実させた
- zmm自体のvesion
- scalaのversion
- sbtのversion
を表示するようにした。
Declineよくできてんな〜
=> Version表示用フラグを拡充する

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala
ffmpegが`output_with_bgm.mp4`を上書きできないケースがあるという報告を受けたため、事前にzmm側で削除することにした。
加えて、相対パスの形式がバラバラだったので可能な範囲で統一した。
=> ffmpegが上書きに失敗するケースに対応する

.github/workflows/ci.yml, .gitignore, project/plugins.sbt, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/CliOptions.scala, src/main/scala/com/github/windymelt/zmm/Main.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/ScreenShot.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/VoiceVox.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/ChromeScreenShot.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/VoiceVox.scala, src/main/scala/com/github/windymelt/zmm/util/Dict.scala, src/main/scala/com/github/windymelt/zmm/util/UtilComponent.scala, src/test/scala/com/github/windymelt/zmm/UnitSpec.scala, src/test/scala/com/github/windymelt/zmm/domain/model/ContextSpec.scala, src/test/scala/com/github/windymelt/zmm/util/UtilSpec.scala
solves: #
- scalafmtは導入されているが、自動的に適用はされていない
- 自動的に適用することで、コントリビュートによるコードスタイルの差分を吸収する
- 一般に、この手のフォーマッタには忠実に従うほうが良いとされている
- scalafmtをsbtに入れる
- scalafmtがCIで実行されるようにする
- 自動でフォーマットされていないという状況
場合によりフォーマットの設定は随時変更する。
=> 自動的にscalafmtする

src/main/resources/reference.conf, src/main/scala/com/github/windymelt/zmm/ChromiumCli.scala, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/CliOptions.scala, src/main/scala/com/github/windymelt/zmm/FirefoxCli.scala, src/main/scala/com/github/windymelt/zmm/Main.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/ScreenShot.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/ChromeScreenShot.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FirefoxScreenShotComponent.scala
solves: #
- Chromeには妙なバグがあり、画面の解像度が800x600くらいになってしまうことがある(バージョンによる)
- 一時的な回避策としてFirefoxを使えるようにしたい
- Firefoxにもスクショを撮影するオプションがあるので、既存のインターフェイスを一部修正しつつ実装した。
- Firefoxは出力先ファイル名を指定できない(指定できるという情報があるが、手元で動作しなかった)ので、Mutexを使って同時に走れなくした
- Mutexを導入したのでIO型になった
- `-s firefox`オプションをつけるとFirefoxで稼動するようになる
Firefoxは透過背景でのスクショをサポートしていないので、動画との組み合わせが今後あるなら問題になるかも
=> Firefoxでもスクショが取れるようにする

.github/workflows/ci.yml
solves: #
- 
- forkしたrepoからのpull reqだと原理上checkoutに失敗してるので
- https://github.com/windymelt/zmm/pull/35#issuecomment-1912948467
- forkされた場合のrepoの場合は一旦暫定的にskip
- 別途、(おそらくやってないので？)scalafmtAllCheckやscalafmtSbtCheckを入れるべきだと思うが、一旦入れてない
- そもそも、forkしてない場合においても、デフォルトのtokenでpushするとCIが動かないので、この方法自体が(少なくとも独自token設定するか何かでもっと工夫しないと) 色々微妙だと思う
=> forkしたrepoからのpull reqでscalafmt失敗する問題修正

.github/workflows/ci.yml
solves: #
- 
- これダメだった https://github.com/windymelt/zmm/pull/66
- 別の方法で判断
- 本当は `github.event.pull_request.user.login` よりもっといい方法ある気がするけど暫定的に
=> forkからpull reqした場合scalafmt失敗するのでskip

src/main/scala/com/github/windymelt/zmm/infrastructure/ChromeScreenShot.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FirefoxScreenShotComponent.scala
solves: #
- 
- Scala 3で警告が出るため
- (すごく大昔のScalaでは意味がある場合があったが)今のScalaではobjectはfinalであって、つける意味が実質ないため
- final消した
=> objectにfinalが付与されているのを削除

.github/workflows/ci.yml, project/metals.sbt, project/project/metals.sbt, project/project/project/metals.sbt
solves: #
- 
- https://github.com/windymelt/zmm/pull/70 こっちでforkからのpull reqの場合はskipしている
- 細かい部分でscalafmtのcheck処理が足りない
- 別途、普通のテストの前にcheckのtaskも実行するようにした
- (どこで失敗したのかわかりやすいように)sbtをそれぞれ(2回)起動して、処理を分けてもいいが、好みの問題感というか、細かいトレードオフがあるが、そこは任せた(?) 
- scalafmtAllだけだとbuild fileはformatされないので、それも追加した
- `DO NOT EDIT! This file is auto-generated.` と書いてあるが、scalafmtSbtしたらformatされたので(そうしないとCI通らなくなるはずなので？)それもコミットしたが・・・？ 🤔
=> CIでのscalafmt関連処理修正

src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala
solves: #
- 
- Scala 2.13.12だと警告
- Scala 3だとエラー
```
[warn] /home/runner/work/zmm/zmm/src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala:64:16: Implicit definition should have explicit type (inferred cats.Monoid[com.github.windymelt.zmm.domain.model.Context]) [quickfixable]
[warn]   implicit val monoidForContext = new Monoid[Context] {
[warn]                ^
```
- 型書いた
=> implicitな `Monoid[Context]` の明示的な型を明記

.github/workflows/ci.yml
solves: #
- CIでscalafmtを自動的にかけるようにしていた
- botなどはpermissionなどの問題で実行できない。
- このためCIがコケたりして実質的に意味がない
- CIでscalafmtかけるのをやめる
- かわりに`scalafmtCheckAll`させて失敗したらコケさせる
- scalafmtは手元でやればよい
=> no auto format in CI

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/Main.scala, src/main/scala/com/github/windymelt/zmm/application/Init.scala
solves: #
- `Cli.scala`がごちゃごちゃしているのでいったん整備したい
- リファクタして見通しをよくしたい
- とりあえずinitializeProjectを移動した
=> CLIの内部をリファクタする

build.sbt, docker-compose.yml, sample.xml
solves: #85
- ZMMにはフォントが同梱されていない
- フォントがうまくレンダされず豆腐になっているという報告が寄せられた
- フリーフォントでありライセンス上問題なければDockerイメージに同梱していいはず
- フォントディレクトリの指定もうまくいっていない様子だった
- Rounded M+をDockerイメージの生成過程で同梱した (ライセンス http://jikasei.me/font/rounded-mplus/license.html)
- フォント指定のディレクトリを`/root/.fonts`から`/usr/share/fonts/zmm`に変更した
- ffmpegのバージョンが更新されてDockerイメージビルドがコケていたので追従
デフォルトでは`unzip`が入っていないのでイメージに同梱した。
=> フリーフォント(Rounded M+)を同梱する + フォントディレクトリ修正 ほか

build.sbt
solves: #
- logbackには`module-info.class`というファイルが入っているが、Scalaには関係がないので無視したい
- 複数のライブラリが`module-info.class`を持っており、uberjarを作るときにconflictする
- merge strategyを追加してfirstにした
=> add merge strategy for module-info.class

sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/util/PathAlias.scala, src/main/twirl/sample.scala.html, src/main/twirl/script.scala.xml, src/test/scala/com/github/windymelt/zmm/util/PathAliasSpec.scala
solves: #
- ZMMはブラウザによるレンダリングやffmpegによる合成を利用しているため、文脈によってカレントディレクトリが異なる
- ブラウザからはテンプレートHTMLから見たパスを用いて画像ファイルのパスを指定しなければならない
- XMLファイルにこのパスの問題が露出しており、使いづらい状態になっていた
- ユーザがこの差異を知る必要は全くない
- `@assets/foo.png`といった記法を導入した(`tsconfig`などで見るおなじみの記法)
- この記法は自動的にブラウザやffmpegの文脈によって読み替えられ、適切なパスに変換されるためエンドユーザはこの記法で書けばよい
- サンプルXMLファイル、テンプレートXMLファイルの追従
- テスト
=> アセット向けのエイリアス記法を導入

src/main/scala/com/github/windymelt/zmm/infrastructure/VoiceVox.scala
solves: https://github.com/windymelt/zmm/issues/94
- タイムアウトの警告出る
- http4sを更新したところ警告が出るようになった
- timeoutを短くする(これで問題ない)
=> reduce timeout to 5 min
