docs/sm41365185.xml
https://www.nicovideo.jp/watch/sm41365185 をupしたのでその原稿を公開する
=> sm41365185 xml file

sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/VoiceVox.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/VoiceVox.scala
特定の単語の発音を指定できていなかったので、XML上で設定できるようにしたい。
`dict`タグを用意した。`meta`中の`dict`タグに`pronounce`属性とともに使うことで発音とアクセントを設定可能。`_`をアクセントが下がる箇所に配置する。
=> VOICEVOXを前提とした辞書機能を追加した

sample.xml, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala
今までは手でBGMを仕込んでいたが、さすがに大変なのでContextの枠組みでなんとかできたい
`bgm`属性でBGMへのパスを指示することにより、その箇所で指定したBGMを流せるようにした
=> BGM機能を実装した

docs/sm41405183.xml
https://www.nicovideo.jp/watch/sm41405183
=> sm41405183

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/util/UtilComponent.scala, src/test/scala/com/github/windymelt/zmm/util/UtilSpec.scala
リファクタリングを行った。
タプル同士の合成を`<*`(`productL`)でうまく表現できたのでそれを使うことにした。
また`foldLeft`のかわりに`foldRight`を使った。こちらのほうが素直に書けた。
分離したついでにテストも書いておいた。
=> BGMまわりのリファクタ

src/main/scala/com/github/windymelt/zmm/Cli.scala
=> Refactoring

docs/sm41450465.xml
https://www.nicovideo.jp/watch/sm41450465
=> sm41450465

docs/sm41459705.xml
https://www.nicovideo.jp/watch/sm41459705
=> sm41459705

project/plugins.sbt
`sbt assembly`でuberjarを作成できるようにした。作成したJARファイルは`java -jar hoge.jar`で実行可能。いろいろ直すべきところがあるがとりあえずJARは作れるようになった
=> added sbt-assembly

build.sbt, src/main/resources/reference.conf, src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/Main.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/VoiceVox.scala, src/main/scala/com/github/windymelt/zmm/util/UtilComponent.scala
いろいろガバだったので整えた。
- 設定ファイル
- `application.conf`を指定できるようにした。これを使ってVOICEVOXのAPIを設定できる
- コマンドラインパーサ
- Declineを導入した。ファイル名を渡せば変換するし、`show voicevox`サブコマンドを与えるとID情報をくれるようにした。
=> アプリケーションとしての体裁を整える

build.sbt, project/plugins.sbt
=> release process

build.sbt
これがないとmavenにpublishしようとするのでskipさせる
=> fix publish

docs/sm41524639.xml
https://www.nicovideo.jp/watch/sm41524639
=> sm41524639

.github/workflows/ci.yml
Example result: https://github.com/y-yu/zmm/actions/runs/3847766680/jobs/6554644318
=> CIのためにGitHub Actions設定追加

docs/sm41810130.xml
https://www.nicovideo.jp/watch/sm41810130
=> sm41810130

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/util/Dict.scala, src/test/scala/com/github/windymelt/zmm/UnitSpec.scala, src/test/scala/com/github/windymelt/zmm/domain/model/ContextSpec.scala, src/test/scala/com/github/windymelt/zmm/util/DictSpec.scala, src/test/scala/com/github/windymelt/zmm/util/UtilSpec.scala
=> 辞書まわりのテストを追加

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/domain/model/Context.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala
solves: #
- 無音で字幕だけ表示したいことがある
- 無音で字幕だけ出したい
- 実際は喋らないダミーユーザを設定することで解決できる
- `by="silent"`で実際には喋らないユーザを設定できるようにした
字幕の色などはあとで調整する
=> by="silent"を指定することで無音期間を作れるようにした

src/main/scala/com/github/windymelt/zmm/Cli.scala, src/main/scala/com/github/windymelt/zmm/CliOptions.scala, src/main/scala/com/github/windymelt/zmm/Main.scala, src/main/scala/com/github/windymelt/zmm/domain/repository/FFmpeg.scala, src/main/scala/com/github/windymelt/zmm/infrastructure/FFmpeg.scala
solves: #36
- 出力先ファイル名を指定したいという要望がある
- 現在その方法がない
- `-o` オプションを新設した。パスを指定することで出力先を指定する。
=> Output file name

.github/workflows/ci.yml
solves: #
- 
- 大昔はどうだったか謎だが、最近は勝手にinstallされていて、普通それで十分なため
- curlでscriptをdownloadしてる部分消した
=> CIでの明示的なsbtのinstall手順削除

src/main/scala/com/github/windymelt/zmm/domain/model/Filter.scala
solves: #91
- 従前は口パクは強制で、`立ち絵.png`に対して口を閉じた`立ち絵!.png`を用意する必要があった
- 何もしないと立ち絵が点滅する
- 口を閉じた画像が存在しない場合はフォールバックさせる
何度もファイルの存在確認をすると遅いし負担になるので結果はキャッシュされる
=> 口パク用のファイルが存在しない場合はオリジナルの立ち絵にフォールバックする
